### ISSUE TITLE
Crawler fails with  URIError: URI malformed

### ISSUE THREAD

**Issue by nippoolg** [qualweb/crawler#2]
Hello, can't get what the problem, trying to crawl domain: https://www.tuusula.fi/ and getting following error:
 URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at \salvia-function\node_modules\@qualweb\crawler\dist\index.js:222:64
    at Array.map (<anonymous>)
    at Crawler.normalizeAndSort (\salvia-function\node_modules\@qualweb\crawler\dist\index.js:222:53)
    at Crawler.fetchPageLinks (\salvia-function\node_modules\@qualweb\crawler\dist\index.js:208:21)

"@qualweb/crawler": 
      "version": "0.3.9"

Any hints or advice would be appreciated! THank you.

**Comment by AntonioEstriga** [comment]
Hi!
It's working in the current version of the code. For new issues please report them in the monorepo https://github.com/qualweb/qualweb.
